### ISSUE TITLE
1.0 TODO

### ISSUE THREAD

**Issue by felipefcm** [felipefcm/seabound#1]
Data model
- [ ] Ship
- [ ] City
- [ ] Player
- [ ] MarketItem
- [ ] Item
- [ ] Route
- [ ] RouteList
- [ ] Game

User interface
- [ ] Main menu
- [ ] New game
- [ ] Choose hometown
- [ ] Main game
- [ ] Travel
- [ ] Travel event

Project setup
- [ ] Set viewport size
- [ ] Create VSCode workspace
- [ ] Check GDScript strong typing docs

City generation
- [ ] Select random name
- [ ] Select random coordinates
- [ ] Select random population number
- [ ] Make sure cities are not too close to each other (min distance param)
- [ ] Make sure very populated cities are not too close to each other

City routes generation (for every `City`)
- [ ] Select random number of routes (`n in [minRoutes, maxRoutes]`)
- [ ] Select `n` closest cities and create `Route`s
- [ ] Do not store duplicate routes, e.g. (A -> B and B -> A)
- [ ] Create functions that query `RouteList` and returns fastest/shortest/safest routes to a `City` (may return more than one if cities are not directly connected)

Create new game
- [ ] Generate cities
- [ ] Generate `RouteList`
- [ ] For every `Item` type, select random supply coordinate
- [ ] Make sure supply points are not too close to each other
- [ ] Write function that determines `Item` price for `City`, given distance to supply point
